In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
import warnings
warnings.filterwarnings('ignore')
from matplotlib import rc
rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False

In [23]:
data = pd.read_csv('ins_fraud.csv')
data.head()

fraud  c1  c2  c3  c4  c5  c6   c7  c8  c9  ...       c15  c16  c17  c18  \
0      0   2   1   3   0   2   0  100   2   0  ...         0    1    0    0   
1      0   1   0   4   0   4   0    0   3   1  ...         0    1    1    1   
2      0   1   0   4   1   4   0  100   3   1  ...  12925040    3    1    0   
3      0   3   1   3   0   4   0    0   2   0  ...         0    3    1    0   
4      0   1   0   1   0   1   0  100   1   0  ...   1209410    1    0    0   

   c19  c20  c21  c22  c23  c24  
0    1    0    0    0   -1    0  
1    2    1    1    1    0    1  
2    2    1    1    1    0    1  
3    1    0    0    0   -1    0  
4    2    0    0    0   -1    0  

[5 rows x 25 columns]

In [24]:
data0 = data[data['fraud']==0]
data1 = data[data['fraud']==1]

In [25]:
data0

fraud  c1  c2  c3  c4  c5  c6   c7  c8  c9  ...       c15  c16  c17  \
0          0   2   1   3   0   2   0  100   2   0  ...         0    1    0   
1          0   1   0   4   0   4   0    0   3   1  ...         0    1    1   
2          0   1   0   4   1   4   0  100   3   1  ...  12925040    3    1   
3          0   3   1   3   0   4   0    0   2   0  ...         0    3    1   
4          0   1   0   1   0   1   0  100   1   0  ...   1209410    1    0   
...      ...  ..  ..  ..  ..  ..  ..  ...  ..  ..  ...       ...  ...  ...   
15995      0   2   0   2   0   2   0  100   2   0  ...         0    1    1   
15996      0   2   0   2   1   4   0  100   1   1  ...         0    2    1   
15997      0   2   1   2   0   4   0  100   1   0  ...         0    0    0   
15998      0   2   0   2   0   2   0  100   2   0  ...         0    4    1   
15999      0   2   0   2   0   1   0  100   1   0  ...   1188750    2    0   

       c18  c19  c20  c21  c22  c23  c24  
0        0    1    0    0    0   -1    0  
1        1    2    1    1    1    0    1  
2        0    2    1    1    1    0    1  
3        0    1    0    0    0   -1    0  
4        0    2    0    0    0   -1    0  
...    ...  ...  ...  ...  ...  ...  ...  
15995    0    1    0    0    0   -1    0  
15996    0    1    0    0    0   -1    0  
15997    0    1    0    0    0   -1    1  
15998    0    1    0    0    0   -1    0  
15999    0    1    0    0    0   -1    0  

[15959 rows x 25 columns]

In [26]:
data1

fraud  c1  c2  c3  c4  c5  c6   c7  c8  c9  ...       c15  c16  c17  \
6          1   1   1   3   0   4   0  100   3   0  ...   1217280    0    0   
18         1   1   0   1   0   4   0  100   1   0  ...         0    1    0   
45         1   2   0   1   0   2   0  100   1   1  ...         0    0    1   
60         1   1   0   3   0   3   0  100   3   0  ...         0    0    1   
83         1   2   0   2   0   1   0  100   1   0  ...         0    1    0   
100        1   2   0   2   0   1   0  100   1   0  ...         0    2    0   
119        1   2   1   5   0   4   0  100   3   1  ...   4192150    0    0   
143        1   2   0   1   0   3   0   40   2   1  ...         0    4    0   
163        1   2   0   4   0   2   0  100   3   0  ...    963800    2    0   
182        1   2   0   3   1   4   0  100   1   0  ...         0    0    0   
199        1   1   0   3   1   4   0    0   1   0  ...         0    1    1   
214        1   2   0   2   0   2   0  100   1   0  ...   1110260    0    1   
230        1   2   0   3   0   4   0  100   2   0  ...         0    0    1   
247        1   2   0   2   0   1   0  100   1   1  ...    520500    0    1   
263        1   2   0   1   0   4   0  100   1   0  ...    800000    0    0   
282        1   2   1   2   0   3   0  100   1   1  ...    670000    0    1   
301        1   1   0   4   0   1   0  100   3   0  ...         0    2    0   
325        1   1   1   4   0   1   0  100   1   0  ...    360000    0    0   
344        1   3   0   2   0   4   0  100   2   0  ...    471700    0    1   
364        1   2   0   3   1   4   0  100   1   0  ...         0    1    0   
383        1   2   0   2   1   4   0  100   1   0  ...   1014600    2    0   
401        1   1   0   4   0   1   0  100   1   0  ...         0    4    0   
417        1   1   0   3   0   4   0  100   3   0  ...  14865500    1    1   
436        1   2   0   3   0   2   0  100   2   0  ...   1014810    2    0   
451        1   2   0   4   0   1   0  100   1   0  ...         0    2    1   
467        1   1   0   3   0   3   0  100   1   1  ...         0    1    0   
481        1   2   1   2   0   2   0  100   1   0  ...    320000    0    0   
496        1   1   0   2   0   2   0  100   1   0  ...         0    4    0   
512        1   2   0   1   0   1   0  100   3   0  ...         0    2    1   
528        1   2   0   3   0   4   0  100   3   0  ...         0    2    0   
545        1   3   1   4   0   4   0  100   2   0  ...    351260    1    0   
561        1   2   0   1   0   1   0  100   1   0  ...    355460    0    0   
579        1   1   0   3   0   1   0  100   1   0  ...   1372160    0    0   
739        1   1   0   1   0   3   0  100   1   0  ...   1286210    0    1   
4671       1   1   0   1   0   1   0  100   2   0  ...   7860220    1    1   
5099       1   1   0   2   0   1   0  100   1   0  ...         0    2    1   
5515       1   1   0   1   0   4   0  100   2   0  ...         0    1    1   
5647       1   2   0   1   0   3   0  100   1   0  ...   1281340    1    1   
7124       1   2   0   1   0   1   0  100   1   0  ...         0    1    1   
9926       1   1   0   1   0   1   0  100   3   0  ...    263261    1    0   
11179      1   2   0   1   0   2   0  100   1   0  ...         0    1    1   

       c18  c19  c20  c21  c22  c23  c24  
6        0    1    1    2    1    2    0  
18       0    2    0    0    0   -1    0  
45       0    1    0    0    0   -1    0  
60       0    1    0    0    0   -1    0  
83       0    1    0    0    0   -1    0  
100      1    1    0    0    0   -1    1  
119      0    1    2    1    1    2    0  
143      0    1    1    2    1    1    0  
163      0    1    1    2    1    0    0  
182      0    1    0    0    0   -1    1  
199      0    1    1    1    1    0    1  
214      0    1    1    1    1    2    0  
230      0    1    0    0    0   -1    0  
247      0    1    1    1    1    1    1  
263      1    1    1    2    1    1    0  
282      0    1    3    2    1    2    1  

In [27]:
data=data0

In [28]:
data

fraud  c1  c2  c3  c4  c5  c6   c7  c8  c9  ...       c15  c16  c17  \
0          0   2   1   3   0   2   0  100   2   0  ...         0    1    0   
1          0   1   0   4   0   4   0    0   3   1  ...         0    1    1   
2          0   1   0   4   1   4   0  100   3   1  ...  12925040    3    1   
3          0   3   1   3   0   4   0    0   2   0  ...         0    3    1   
4          0   1   0   1   0   1   0  100   1   0  ...   1209410    1    0   
...      ...  ..  ..  ..  ..  ..  ..  ...  ..  ..  ...       ...  ...  ...   
15995      0   2   0   2   0   2   0  100   2   0  ...         0    1    1   
15996      0   2   0   2   1   4   0  100   1   1  ...         0    2    1   
15997      0   2   1   2   0   4   0  100   1   0  ...         0    0    0   
15998      0   2   0   2   0   2   0  100   2   0  ...         0    4    1   
15999      0   2   0   2   0   1   0  100   1   0  ...   1188750    2    0   

       c18  c19  c20  c21  c22  c23  c24  
0        0    1    0    0    0   -1    0  
1        1    2    1    1    1    0    1  
2        0    2    1    1    1    0    1  
3        0    1    0    0    0   -1    0  
4        0    2    0    0    0   -1    0  
...    ...  ...  ...  ...  ...  ...  ...  
15995    0    1    0    0    0   -1    0  
15996    0    1    0    0    0   -1    0  
15997    0    1    0    0    0   -1    1  
15998    0    1    0    0    0   -1    0  
15999    0    1    0    0    0   -1    0  

[15959 rows x 25 columns]

In [29]:
data = data[data['c6']==0] # c6 법인이용 개인 고객 = 0 / 법인 = 1 / 법인 구성원 = 2
data = data[(data['c7']==0) | (data['c7']==40) | (data['c7']==100)] # c7 과실율 unique = 100,   0,  90,  55,  30,  80,  40,  10,  70,  20,  60,  85,  75, 50,  15,  65,  25
data = data[data['c12']!=5] # c12 대여기간 (2,3,4,5) : 1 / (6,7,8,9) : 2 / (10 =< x <=36) : 3 / (36+) : 4 / (0,1) : 5
data = data[(data['c19']==1) | (data['c19']==2) | (data['c19']==3)] # c19 수리 부위 갯수
data['c25'] = data['c15']-data['c14'] # c25 : 보험사 손해비용 - 차량수리비용

In [30]:
data

fraud  c1  c2  c3  c4  c5  c6   c7  c8  c9  ...  c16  c17  c18  c19  \
0          0   2   1   3   0   2   0  100   2   0  ...    1    0    0    1   
1          0   1   0   4   0   4   0    0   3   1  ...    1    1    1    2   
2          0   1   0   4   1   4   0  100   3   1  ...    3    1    0    2   
3          0   3   1   3   0   4   0    0   2   0  ...    3    1    0    1   
4          0   1   0   1   0   1   0  100   1   0  ...    1    0    0    2   
...      ...  ..  ..  ..  ..  ..  ..  ...  ..  ..  ...  ...  ...  ...  ...   
15994      0   2   0   3   1   4   0  100   1   0  ...    0    0    0    1   
15995      0   2   0   2   0   2   0  100   2   0  ...    1    1    0    1   
15996      0   2   0   2   1   4   0  100   1   1  ...    2    1    0    1   
15997      0   2   1   2   0   4   0  100   1   0  ...    0    0    0    1   
15998      0   2   0   2   0   2   0  100   2   0  ...    4    1    0    1   

       c20  c21  c22  c23  c24           c25  
0        0    0    0   -1    0 -1.302547e+05  
1        1    1    1    0    1  0.000000e+00  
2        1    1    1    0    1  1.266691e+07  
3        0    0    0   -1    0 -1.341009e+06  
4        0    0    0   -1    0  6.853794e+05  
...    ...  ...  ...  ...  ...           ...  
15994    0    0    0   -1    0 -6.672931e+05  
15995    0    0    0   -1    0  0.000000e+00  
15996    0    0    0   -1    0 -6.184394e+05  
15997    0    0    0   -1    1  0.000000e+00  
15998    0    0    0   -1    0  0.000000e+00  

[13895 rows x 26 columns]

In [31]:
def outliers_iqr(data):
    q1, q3 = np.percentile(data, [25,75])
    iqr = q3 - q1
    lower_bound = q1 - (iqr * 1.5)
    upper_bound = q3 + (iqr * 1.5)
    
    return np.where((data > upper_bound)|(data < lower_bound))

In [32]:
c25_outlier_index = outliers_iqr(data['c25'])[0]

In [33]:
c25_not_outlier_index = []

for i in data.index:
    if i not in c25_outlier_index:
        c25_not_outlier_index.append(i)

In [34]:
c25_outlier_index

array([    2,     3,     5, ..., 13879, 13887, 13888])

In [35]:
c25_not_outlier_index = np.array(c25_not_outlier_index)

In [36]:
data = data.loc[c25_not_outlier_index]

In [37]:
len(data[data["fraud"] == 1])

0

In [38]:
final = pd.concat([data, data1])
final = final.drop(['c25'], 1)

In [39]:
final

fraud  c1  c2  c3  c4  c5  c6   c7  c8  c9  ...      c15  c16  c17  \
0          0   2   1   3   0   2   0  100   2   0  ...        0    1    0   
1          0   1   0   4   0   4   0    0   3   1  ...        0    1    1   
4          0   1   0   1   0   1   0  100   1   0  ...  1209410    1    0   
7          0   3   1   3   0   4   0  100   3   1  ...   250000    2    0   
8          0   2   0   4   0   4   0    0   1   0  ...        0    1    0   
...      ...  ..  ..  ..  ..  ..  ..  ...  ..  ..  ...      ...  ...  ...   
5515       1   1   0   1   0   4   0  100   2   0  ...        0    1    1   
5647       1   2   0   1   0   3   0  100   1   0  ...  1281340    1    1   
7124       1   2   0   1   0   1   0  100   1   0  ...        0    1    1   
9926       1   1   0   1   0   1   0  100   3   0  ...   263261    1    0   
11179      1   2   0   1   0   2   0  100   1   0  ...        0    1    1   

       c18  c19  c20  c21  c22  c23  c24  
0        0    1    0    0    0   -1    0  
1        1    2    1    1    1    0    1  
4        0    2    0    0    0   -1    0  
7        0    1    1    1    1    1    1  
8        0    1    1    1    1    2    0  
...    ...  ...  ...  ...  ...  ...  ...  
5515     0    1    1    1    1    0    0  
5647     0    2    1    1    1    2    0  
7124     0    1    0    0    0   -1    0  
9926     1    1    0    0    0   -1    0  
11179    0    1    1    1    1    1    0  

[12223 rows x 25 columns]

In [40]:
len(final[final["fraud"] == 1])

41

In [41]:
data = final

In [42]:
data

fraud  c1  c2  c3  c4  c5  c6   c7  c8  c9  ...      c15  c16  c17  \
0          0   2   1   3   0   2   0  100   2   0  ...        0    1    0   
1          0   1   0   4   0   4   0    0   3   1  ...        0    1    1   
4          0   1   0   1   0   1   0  100   1   0  ...  1209410    1    0   
7          0   3   1   3   0   4   0  100   3   1  ...   250000    2    0   
8          0   2   0   4   0   4   0    0   1   0  ...        0    1    0   
...      ...  ..  ..  ..  ..  ..  ..  ...  ..  ..  ...      ...  ...  ...   
5515       1   1   0   1   0   4   0  100   2   0  ...        0    1    1   
5647       1   2   0   1   0   3   0  100   1   0  ...  1281340    1    1   
7124       1   2   0   1   0   1   0  100   1   0  ...        0    1    1   
9926       1   1   0   1   0   1   0  100   3   0  ...   263261    1    0   
11179      1   2   0   1   0   2   0  100   1   0  ...        0    1    1   

       c18  c19  c20  c21  c22  c23  c24  
0        0    1    0    0    0   -1    0  
1        1    2    1    1    1    0    1  
4        0    2    0    0    0   -1    0  
7        0    1    1    1    1    1    1  
8        0    1    1    1    1    2    0  
...    ...  ...  ...  ...  ...  ...  ...  
5515     0    1    1    1    1    0    0  
5647     0    2    1    1    1    2    0  
7124     0    1    0    0    0   -1    0  
9926     1    1    0    0    0   -1    0  
11179    0    1    1    1    1    1    0  

[12223 rows x 25 columns]

## 언더 샘플링

### RandomUnderSampler

In [22]:
X = data.drop("fraud", 1)
y = data["fraud"]

In [23]:
from imblearn.under_sampling import RandomUnderSampler 
rus = RandomUnderSampler(random_state=42)
X_res, y_res = rus.fit_resample(X, y)

In [24]:
#from collections import Counter
#print('Resampled dataset shape %s' % Counter(y))

In [25]:
from sklearn.model_selection import train_test_split
 
X = X_res
y = y_res
 
# 테스트 데이터 30%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify = y)
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

57
25
57
25


In [26]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics    
 
# 학습 진행
forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train, y_train)
 
# 예측
y_pred = forest.predict(X_test)
print(y_pred)
print(list(y_test))
 
# 정확도 확인
print('정확도 :', metrics.accuracy_score(y_test, y_pred))

print('precision', metrics.precision_score(y_test, y_pred))

print('recall', metrics.recall_score(y_test, y_pred))

print('f1', metrics.f1_score(y_test, y_pred))

[0 0 1 1 0 0 1 1 0 0 0 0 1 0 1 0 1 1 1 0 0 1 0 0 0]
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1]
정확도 : 0.56
precision 0.6
recall 0.46153846153846156
f1 0.5217391304347826


### Tomek’s link method

In [27]:
X = data.drop("fraud", 1)
y = data["fraud"]

In [28]:
from imblearn.under_sampling import TomekLinks
tom = TomekLinks()
X_tom, y_tom = tom.fit_resample(X, y)

In [29]:
from sklearn.model_selection import train_test_split
 
X = X_tom
y = y_tom
 
# 테스트 데이터 30%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify = y)
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

8541
3661
8541
3661


In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics    
 
# 학습 진행
forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train, y_train)
 
# 예측
y_pred = forest.predict(X_test)
print(y_pred)
print(list(y_test))
 
# 정확도 확인
print('정확도 :', metrics.accuracy_score(y_test, y_pred))

print('precision', metrics.precision_score(y_test, y_pred))

print('recall', metrics.recall_score(y_test, y_pred))

print('f1', metrics.f1_score(y_test, y_pred))

[0 0 0 ... 0 0 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

### Condensed Nearest Neighbour

In [31]:
X = data.drop("fraud", 1)
y = data["fraud"]

In [32]:
from imblearn.under_sampling import CondensedNearestNeighbour
cnn = CondensedNearestNeighbour(random_state=42)
X_cnn, y_cnn = cnn.fit_resample(X, y)

In [33]:
from sklearn.model_selection import train_test_split
 
X = X_cnn
y = y_cnn
 
# 테스트 데이터 30%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify = y)
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

293
126
293
126


In [34]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics    
 
# 학습 진행
forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train, y_train)
 
# 예측
y_pred = forest.predict(X_test)
print(y_pred)
print(list(y_test))
 
# 정확도 확인
print('정확도 :', metrics.accuracy_score(y_test, y_pred))

print('precision', metrics.precision_score(y_test, y_pred))

print('recall', metrics.recall_score(y_test, y_pred))

print('f1', metrics.f1_score(y_test, y_pred))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
정확도 : 0.9047619047619048
precision 0.0
recall 0.0
f1 0.0


### One Sided Selection

In [35]:
X = data.drop("fraud", 1)
y = data["fraud"]

In [36]:
from imblearn.under_sampling import OneSidedSelection
oss = OneSidedSelection(random_state=0)
X_oss, y_oss = oss.fit_resample(X, y)

In [37]:
from sklearn.model_selection import train_test_split
 
X = X_oss
y = y_oss
 
# 테스트 데이터 30%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify = y)
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

8208
3519
8208
3519


In [38]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics    
 
# 학습 진행
forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train, y_train)
 
# 예측
y_pred = forest.predict(X_test)
print(y_pred)
print(list(y_test))
 
# 정확도 확인
print('정확도 :', metrics.accuracy_score(y_test, y_pred))

print('precision', metrics.precision_score(y_test, y_pred))

print('recall', metrics.recall_score(y_test, y_pred))

print('f1', metrics.f1_score(y_test, y_pred))

[0 0 0 ... 0 0 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

### Edited Nearest Neighbours

In [39]:
X = data.drop("fraud", 1)
y = data["fraud"]

In [58]:
from imblearn.under_sampling import EditedNearestNeighbours
enn = EditedNearestNeighbours(kind_sel="all", n_neighbors=5)
X_enn, y_enn = enn.fit_resample(X, y)

In [59]:
from sklearn.model_selection import train_test_split
 
X = X_enn
y = y_enn
 
# 테스트 데이터 30%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify = y)
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

8460
3627
8460
3627


In [60]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics    
 
# 학습 진행
forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train, y_train)
 
# 예측
y_pred = forest.predict(X_test)
print(y_pred)
print(list(y_test))
 
# 정확도 확인
print('정확도 :', metrics.accuracy_score(y_test, y_pred))

print('precision', metrics.precision_score(y_test, y_pred))

print('recall', metrics.recall_score(y_test, y_pred))

print('f1', metrics.f1_score(y_test, y_pred))

[0 0 0 ... 0 0 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 

### Neighbourhood Cleaning Rule

In [61]:
X = data.drop("fraud", 1)
y = data["fraud"]

In [62]:
from imblearn.under_sampling import NeighbourhoodCleaningRule
ncr = NeighbourhoodCleaningRule(kind_sel="all", n_neighbors=5)
X_ncr, y_ncr = ncr.fit_resample(X, y)

In [63]:
from sklearn.model_selection import train_test_split
 
X = X_ncr
y = y_ncr
 
# 테스트 데이터 30%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify = y)
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

8470
3631
8470
3631


In [64]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics    
 
# 학습 진행
forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train, y_train)
 
# 예측
y_pred = forest.predict(X_test)
print(y_pred)
print(list(y_test))
 
# 정확도 확인
print('정확도 :', metrics.accuracy_score(y_test, y_pred))

print('precision', metrics.precision_score(y_test, y_pred))

print('recall', metrics.recall_score(y_test, y_pred))

print('f1', metrics.f1_score(y_test, y_pred))

[0 0 0 ... 0 0 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

## 복합 샘플링

- SMOTEENN: SMOTE + ENN
- SMOTETomek: SMOTE + Tomek

In [43]:
from imblearn.over_sampling import *

### SMOTEENN

In [44]:
X = data.drop("fraud", 1)
y = data["fraud"]

In [45]:
from imblearn.combine import *
stn = SMOTEENN(random_state=0)
X_stn, y_stn = stn.fit_resample(X, y)

In [46]:
from sklearn.model_selection import train_test_split
 
X = X_stn
y = y_stn
 
# 테스트 데이터 30%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify = y)
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

10624
4554
10624
4554


In [47]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics    
 
# 학습 진행
forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train, y_train)
 
# 예측
y_pred = forest.predict(X_test)
print(y_pred)
print(list(y_test))
 
# 정확도 확인
print('정확도 :', metrics.accuracy_score(y_test, y_pred))

print('precision', metrics.precision_score(y_test, y_pred))

print('recall', metrics.recall_score(y_test, y_pred))

print('f1', metrics.f1_score(y_test, y_pred))

[1 0 0 ... 1 1 0]
[1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 

In [48]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[2174,    8],
       [   9, 2363]])

In [49]:
y = data["fraud"]

In [50]:
fraud = data.drop("fraud", 1)

In [51]:
y_pred = forest.predict(fraud)
confusion_matrix(y, y_pred)

array([[12146,    36],
       [   15,    26]])

In [52]:
print('정확도 :', metrics.accuracy_score(y, y_pred))

print('precision', metrics.precision_score(y, y_pred))

print('recall', metrics.recall_score(y, y_pred))

print('f1', metrics.f1_score(y, y_pred))

정확도 : 0.9958275382475661
precision 0.41935483870967744
recall 0.6341463414634146
f1 0.5048543689320388


### SMOTETomek

In [53]:
X = data.drop("fraud", 1)
y = data["fraud"]

In [54]:
from imblearn.combine import *
stt = SMOTETomek(random_state=4)
X_stt, y_stt = stt.fit_resample(X, y)

In [55]:
from sklearn.model_selection import train_test_split
 
X = X_stt
y = y_stt
 
# 테스트 데이터 30%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify = y)
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

15066
6458
15066
6458


In [56]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics    
 
# 학습 진행
forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train, y_train)
 
# 예측
y_pred = forest.predict(X_test)
print(y_pred)
print(list(y_test))
 
# 정확도 확인
print('정확도 :', metrics.accuracy_score(y_test, y_pred))

print('precision', metrics.precision_score(y_test, y_pred))

print('recall', metrics.recall_score(y_test, y_pred))

print('f1', metrics.f1_score(y_test, y_pred))

[0 0 1 ... 0 1 1]
[0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 

In [57]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[3224,    5],
       [  14, 3215]])

In [58]:
y = data["fraud"]

In [59]:
fraud = data.drop("fraud", 1)

In [60]:
y_pred = forest.predict(fraud)
confusion_matrix(y, y_pred)

array([[12172,    10],
       [   19,    22]])

In [61]:
print('정확도 :', metrics.accuracy_score(y, y_pred))

print('precision', metrics.precision_score(y, y_pred))

print('recall', metrics.recall_score(y, y_pred))

print('f1', metrics.f1_score(y, y_pred))

정확도 : 0.9976274237094003
precision 0.6875
recall 0.5365853658536586
f1 0.6027397260273972


In [ ]:
# 데이터 정규분포화
# 캐글 비대칭 데이터
# 강사님 자료 비대칭데이터